### ISSUE TITLE
Is it possible to get last level descendants?

### ISSUE THREAD

**Issue by manicko** [oo12/setPlaceholders#2]
Hi, thank you for the great snippet!

I'm wondering if it is possible to get TVs of descendants from any level?

E.g. I have the following catalog structure

category level 1
-category level 2
--category level3
    -doc1
    -doc2
category2 level 1
-category2 level 2
    -doc1
    -doc2

And I need to put image for each category and sub-category stored on in the random last level document.

Thank you!

**Comment by oo12** [comment]
Hi!

Right now it'll only go down one level, that is, get the immediate children of a given resource.  Children are trickier to handle than parents since a resource only has a single parent on each level of the tree, but can have any number of children. There'd need to be a way of specifying which particular one you want.

I could make the child selector recursive, so you could do something like child.child-1.childR.tv.someTV (meaning get a resource's first child, then that doc's last child, then a TV from a random child of that one).  It's a rather unwieldy syntax (why I didn't add it to begin with :-), but possible.

However, there might be an easier way to do what you need.  I don't quite understand what you're wanting to do though, especially the last sentence.  If I'm guessing right, you want to do this: _for any category, get an image from a random product in the category or one of its sub-categories_.  getResources can do this easily.  If your image TV is named myImage, you'd put this in your category template:

```
[[getResources? &sortby=`RAND()` &limit=`1` &hideContainers=`1` &includeTVs=`1` &includeTVlist=`myImage` &tpl=`myTpl`]]
```

myTpl is a chunk with something like `<img src="[[+tv.myImage]]" alt="[[+pagetitle]]">` or `<img src="[[+tv.myImage:phpthumbof=`w=150&h=100&zc=1`]]" alt="[[+pagetitle]]">`

Does that do what you need?

**Comment by manicko** [comment]
Sorry for my English))
I have documents with TVs containing image path. The same TVs for containers are empty. What I need is to find a way, to get the value of TV from any document within container and set this value to the TV field of this container.

The first thing I tried was chain of arguments like you described: child.child-1.childR.tv.someTV)) This code was not working, so I thought that I was doing something wrong. 

Thank you for the suggestion of using getResources insted! This helped. 
Though I found that there is a bug with using this getResources call  as a default value for TV. If container id is not specified within getResources call the call returns nothing.  Then you will try to output this TVs on any page of your site the output values will be values of the page where your put your output but not the values of documents for which they were set...

I've asked for help on modx.com, so hope that will find solution soon))

**Comment by oo12** [comment]
Your English really isn't bad! This is a bit of a tricky subject to discuss in any language.

Хотя.. можно поменяться местами. Теперь уж мне придется напрячь мозги :-)

Нет, на данный момент такая "цепочка детей" не получится, не предусмотрен такой функционал. Я это уточню в документации в ближайшее время и когда доберусь до следующей версии, наверно добавлю.

Как я понимаю, у вас несколько категорий и уровней подкатегорий, и в них есть кое-какие продукты. У каждого продукта есть картинка (ТV) и вы хотите показать одну из них, случайную, на каждой странице-категории. Значит, у вас есть шаблон "Категория" и шаблон "Продукт", не так ли? И у Категории тоже есть ТVшка для картинки, только она пустая и надо дополнить картинкой продукта какого-нибудь?  Если так, то почему не забыть про TV Категории и более непосредственно вывести картинку продукта, путем вызова getResources в шаблоне Категории? Тот вызов вроде должен работать (я на скорую руку проверил), так как по умолчании будет параметр `&parents=`[[*id]]``. А если же картинка встречается в нескольких местах на странице, то используйте еще и параметр `&toPlaceholder=`kartinka`` в getResources. Тогда УРЛ картинки будет легко доступно с помощью плейсхолдера `[[+kartinka]]`.

Или я что-то недопонимаю?

**Comment by manicko** [comment]
How did you know that I'm from Russia? :)) Anyway many thanks for that lets talk on Russian ))

Все правильно за исключением того, что картинку мне нужно вывести не на странице категории а на главной странице сайта. Поэтому шаблон категории мне не помогает. Если действительно интересна проблема, я приложил картинку как это выглядит в бекэнде и фронтэнде - нарисовать иногда понятнее, чем объяснять на словах)) 

![site](https://f.cloud.github.com/assets/1097057/462310/2bf829e8-b49a-11e2-92ce-081f7a1b39b3.jpg)

**Comment by oo12** [comment]
I just looked at your GitHub activity :-)  Otherwise your English doesn't sound obviously "Russian" (that's good) and I wouldn't have been able to guess.

По идее это то, что надо (в немного упрощенном виде):

```
[[getResources? &parents=`111` &depth=`0` &limit=`0` &sortby=`menuindex` &sortdir=`ASC` &tpl=`catTpl`]]
```

**catTpl**

```
[[!getResources? &parents=`[[+id]]` &limit=`1` &sortby=`RAND()` &hideContainers=`1` &includeTVs=`1` &includeTVlist=`image` &tpl=`catImageTpl`]]

<a href="[[~[[+id]]]]">[[+pagetitle]]</a>

<ul>
[[getResources? &parents=`[[+id]]` &limit=`0` &depth=`0` &sortby=`menuindex` &sortdir=`ASC` &tpl=`catItemTpl`]]
</ul>
```

**catImageTpl**

```
<a href="[[~[[+id]]]]"><img src="[[+tv.image]]" alt="[[+pagetitle]]"></a>
```

**catItemTpl**

```
<li>[[+pagetitle]]</li>
```

Я также добавил возможность повторять `child` (с чего все и началось :-)  Если хотите поэкспериментировать, поменяйте файл core/components/setplaceholders/model/setplaceholders.class.php на вот [эту версию](https://github.com/oo12/setPlaceholders/blob/dev/core/components/setplaceholders/model/setplaceholders.class.php).

**Comment by manicko** [comment]
Thank you for all your help and kindness! 

I used chain:  [[setPlaceholders? &id=`[[+id]]`&ph=`childR.childR.tv.image!!childR.tv.image` &output=`1`]] within a wayfinder call and it works perfectly! 

I also use this snippet: http://modx.com/extras/package/menucaching to cache wayfinder output. So after first calculation it does not take any resources))

**Comment by oo12** [comment]
Great, I'm glad you've got it solved!  Good you're using menuCaching too.
Удачи!
