### ISSUE TITLE
As a getResourceField replacement Preformance?

### ISSUE THREAD

**Issue by Hannes-III** [oo12/setPlaceholders#4]
Sorry it is me again,

I just reread the documentation about the `&output` Property. Is `setPlaceholders` in those two cases as perfomant or is the second way faster?
Two Calles each outputting directly:

```
TV1: [[setPlaceholders? &ph=`Uparent2.tv.TV1` &output=`1`]]
TV2: [[setPlaceholders? &ph=`Uparent2.tv.TV2` &output=`1`]]
```

or one Call and unsing the resulting Placeholders:

```
[[setPlaceholders? &ph=`Uparent2.tv.TV1 || Uparent2.tv.TV2`]]
TV1: [[+sph.Uparent2.tv.TV1]]
TV2: [[+sph.Uparent2.tv.TV2]]
```

Thanks for your Answer,
Regards, Hannes

**Comment by oo12** [comment]
Hmm, good question.  I'll try to do a test this weekend.

setPlaceholders will be faster with the placeholders grouped together like in your second variant, but I'm not sure how the time savings compares with the extra time for the parser to fill in those two placeholders.  My guess is that one way is not appreciably faster than the other, but the second way is cleaner and more readable for the developer, so that's what I'd use.

Actually I'd tweak it like this for maximum readability:

```
[[setPlaceholders? &ph=` foo == Uparent2.tv.TV1 || bar == Uparent2.tv.TV2 `]]
TV1: [[+foo]]
TV2: [[+bar]]
```

using more appropriate placeholder names of course :-)

Either way I'm pretty sure it's faster than using a combination of getResourceField and UltimateParent.

**Comment by Hannes-III** [comment]
thanks for the tip with the naming of placeholder, I have overseen that. I am Courious about the result of the test.

**Comment by oo12** [comment]
I found out that the difference in speed between the two versions in negligible.  One's not faster than the other.

However, I did find that setPlaceholders is 1.5 times faster than the equivalent getResoureField + UltimateParent calls :-)  2.93 ms vs. 4.43 ms on the server I tested it on.

**Comment by Hannes-III** [comment]
Very interesting result I thought that the "cleaner and more readable" variant would have an advantage over the other.
It really outperforms `getResoureField`!

**Comment by Hannes-III** [comment]
Ah jeah, thank you!
