### ISSUE TITLE
Can this be used with phpthumbof?

### ISSUE THREAD

**Issue by abelafonte** [oo12/setPlaceholders#5]
I have an image TV that I am calling via setPlaceholder's prev/next placeholders.  However, when I use the phpthumbof output filter on the returned url, I get the original image.

Does this have something to do with the order in which placeholders are processed in MODX?

**Comment by oo12** [comment]
It ought to work, as far as I can think. If phpthumbof (pThumb) is returning the original URL—the one you gave it—it usually means it wasn't able to find the file (or less commonly, create the thumbnail).  If the TV is using a media source, make sure you use the `&processTVs=`1`` property with setPlaceholders, otherwise you won't get the first part of the path that's stored in the media source config.

The next thing I'd do is remove the output filter and make sure the image is showing up properly.  If you get a broken image, fix that first.  Once you've got that working properly, add the phpthumbof output filter back.

If you want to provide some details I might could give you a more precise answer.

**Comment by abelafonte** [comment]
Oh snap! I didn't realize there was a &processTVs param!  That did the trick.  Btw, best plugin ever.  I'm gonna do a tutorial/write-up on it soon.

**Comment by oo12** [comment]
Cool, I'm glad that fixed things for you and that you find setPlaceholders useful in general.  It's sort of a collection of all those "sure would be handy if I could get X..." moments that have come up while working on different sites.  Yeah, if you do a tutorial be sure to post a link in the MODX forums; I'm sure some people would appreciate it!
